"""
agents/medical_advisor.py — Medical Advice Node
================================================
WHAT IT DOES:
  The final synthesis node. Takes ALL previous agent outputs and generates
  a warm, clear, patient-friendly response with:
  - Possible conditions explained simply
  - Practical self-care tips
  - Warning signs to watch for
  - Clear next steps
  - Medical disclaimer

LANGGRAPH ROLE:
  Final specialist node. Reads everything from state, writes `final_response`.

LANGCHAIN CONCEPT — Multiple input variables in ChatPromptTemplate:
  Here we pass multiple variables from the state into a single prompt template.
  This shows how prompts can be dynamically constructed from rich state data.
"""

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from agents.state import HealthAgentState
from dotenv import load_dotenv
load_dotenv()

ADVICE_SYSTEM = """You are a compassionate, knowledgeable medical advisor AI assistant.
Your job is to translate clinical findings into clear, friendly, actionable health guidance.

Format your response using this exact structure with emojis and markdown:

## 🩺 What Might Be Going On
[Explain the top 1-2 likely conditions in simple, non-alarming language]

## 💊 Self-Care Tips
[3-4 practical home care tips relevant to their symptoms]

## ⚠️ Warning Signs — Seek Immediate Help If:
[3-4 specific red flag symptoms that require urgent medical attention]

## 📋 Recommended Next Steps
[Clear, prioritized action items based on the risk level]

---
⚠️ *This response is generated by an AI for informational and educational purposes only. 
It does NOT constitute a medical diagnosis or professional medical advice. 
Please consult a qualified healthcare professional for proper evaluation and treatment.*
---

Tone: Warm, clear, non-alarming (unless EMERGENCY risk level). Avoid jargon."""


prompt = ChatPromptTemplate.from_messages([
    ("system", ADVICE_SYSTEM),
    ("human", """The patient said: "{user_input}"

Clinical Analysis:
- Symptoms identified: {symptoms}
- Risk level: {risk_level} — {risk_reason}
- Recommended action: {risk_action}
- Top possible conditions:
{conditions_text}

Generate a helpful, patient-friendly response.""")
])

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)
chain = prompt | llm | StrOutputParser()


def medical_advice_node(state: HealthAgentState) -> dict:
    """
    LangGraph Node: Medical Advice (Final Synthesis)

    Input  (from state): Everything — user_input, symptoms, conditions, risk
    Output (to state)  : {"final_response": "..."}
    """
    print("  [Node] MedicalAdvisor running...")

    conditions = state.get("predicted_conditions", [])
    risk = state.get("risk_assessment", {})

    # Format conditions into readable text for the prompt
    conditions_text = "\n".join([
        f"  • {c.get('name', 'Unknown')} ({c.get('probability', 'Unknown')} probability): "
        f"{c.get('reasoning', '')}"
        for c in conditions
    ]) or "  • No specific conditions identified"

    response = chain.invoke({
        "user_input": state.get("user_input", ""),
        "symptoms": ", ".join(state.get("normalized_symptoms", [])),
        "risk_level": risk.get("risk_level", "MEDIUM"),
        "risk_reason": risk.get("reason", ""),
        "risk_action": risk.get("action", "Consult a healthcare provider"),
        "conditions_text": conditions_text
    })

    print("  [Node] Medical advice generated.")
    return {"final_response": response}
