"""
agents/medical_advisor.py — Medical Advice Node
================================================
WHAT IT DOES:
  The final synthesis node. Takes ALL previous agent outputs and generates
  a warm, clear, patient-friendly response with:
  - Possible conditions explained simply
  - Practical self-care tips
  - Warning signs to watch for
  - Clear next steps
  - Medical disclaimer

LANGGRAPH ROLE:
  Final specialist node. Reads everything from state, writes `final_response`.

LANGCHAIN CONCEPT — Multiple input variables in ChatPromptTemplate:
  Here we pass multiple variables from the state into a single prompt template.
  This shows how prompts can be dynamically constructed from rich state data.
"""

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from agents.state import HealthAgentState
from dotenv import load_dotenv
load_dotenv()

ADVICE_SYSTEM = """You are a compassionate, knowledgeable medical advisor AI assistant.
Your job is to translate clinical findings into clear, friendly, actionable health guidance.

Format your response using this exact structure with emojis and markdown:

## 🩺 What Might Be Going On
[Explain the top 1-2 likely conditions in simple, non-alarming language]

## 💊 Self-Care Tips
[3-4 practical home care tips relevant to their symptoms]

## ⚠️ Warning Signs — Seek Immediate Help If:
[3-4 specific red flag symptoms that require urgent medical attention]

## 📋 Recommended Next Steps
[Clear, prioritized action items based on the risk level]

---
⚠️ *This response is generated by an AI for informational and educational purposes only. 
It does NOT constitute a medical diagnosis or professional medical advice. 
Please consult a qualified healthcare professional for proper evaluation and treatment.*
---

Tone: Warm, clear, non-alarming (unless EMERGENCY risk level). Avoid jargon."""


prompt = ChatPromptTemplate.from_messages([
    ("system", ADVICE_SYSTEM),
    ("human", """The patient said: "{user_input}"

Clinical Analysis:
- Symptoms identified: {symptoms}
- Risk level: {risk_level} — {risk_reason}
- Recommended action: {risk_action}
- Top possible conditions:
{conditions_text}

{report_context}

Generate a helpful, patient-friendly response.""")
])

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)
chain = prompt | llm | StrOutputParser()


def medical_advice_node(state: HealthAgentState) -> dict:
    """Updated to include report analysis if available"""

    conditions = state.get("predicted_conditions", [])
    risk = state.get("risk_assessment", {})
    report_analysis = state.get("report_analysis")  # NEW

    conditions_text = "\n".join([
        f"  • {c.get('name')} ({c.get('probability')} probability): {c.get('reasoning')}"
        for c in conditions
    ]) or "  • No specific conditions identified"

    # Build report context if available
    report_context = ""
    if report_analysis:
        abnormal = report_analysis.get("abnormal_findings", [])
        report_context = f"""
Medical Report Analysis:
- Report Type: {report_analysis.get('report_type', 'Unknown')}
- Summary: {report_analysis.get('summary', '')}
- Abnormal Findings: {', '.join(abnormal) if abnormal else 'None detected'}
- Urgency: {report_analysis.get('urgency_level', 'ROUTINE')}
- Doctor Notes: {report_analysis.get('doctor_notes', 'None')}
"""

    response = chain.invoke({
        "user_input": state.get("user_input", ""),
        "symptoms": ", ".join(state.get("normalized_symptoms") or []),
        "risk_level": risk.get("risk_level", "MEDIUM"),
        "risk_reason": risk.get("reason", ""),
        "risk_action": risk.get("action", "Consult a healthcare provider"),
        "conditions_text": conditions_text,
        "report_context": report_context  # NEW
    })

    return {"final_response": response}